### ISSUE TITLE
Add support for Belarus TIN

### ISSUE THREAD

**Issue by unho** [arthurdejong/python-stdnum#196]
According to http://192.167.108.132/img/VAT_by_Countries.pdf and https://en.wikipedia.org/wiki/VAT_identification_number it is called "УНП" (short for "Учетный номер
плательщика") and it is a 9 digit number (for example 190190190).

* https://be.wikipedia.org/wiki/%D0%A3%D0%BB%D1%96%D0%BA%D0%BE%D0%B2%D1%8B_%D0%BD%D1%83%D0%BC%D0%B0%D1%80_%D0%BF%D0%BB%D0%B0%D1%86%D0%B5%D0%BB%D1%8C%D1%88%D1%87%D1%8B%D0%BA%D0%B0
  * Includes algorithm to calculate check digit.
  * Includes examples.
* https://ru.wikipedia.org/wiki/%D0%A3%D1%87%D1%91%D1%82%D0%BD%D1%8B%D0%B9_%D0%BD%D0%BE%D0%BC%D0%B5%D1%80_%D0%BF%D0%BB%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D1%89%D0%B8%D0%BA%D0%B0
* http://www.portal.nalog.gov.by/grp/

* Examples: Visiting https://kartoteka.by/unp-190796490 provides data for the entity with this TIN. At the bottom of that page there are links to other entities pages.
* More examples can be found in https://www.google.com/search?q=%D0%A3%D0%9D%D0%9F+site%3A.by

**Comment by arthurdejong** [comment]
Hi @unho,
Do you happen to know how the check digit is calculated over personal numbers? E.g. WikiPedia mentions МА1953681 but neither using the values in the area table or the values in the last table (Разлік УНП для фізічных асоб) seem to result in a valid check digit. Also, that last section seems to suggest that the check digit should also be a letter for personal numbers which the example isn't.

**Comment by unho** [comment]
@arthurdejong Unfortunately I have no more information on the matter than the one included in the ticket and in the links included in the ticket.

Given that the Wikipedia page provides an algorithm to calculate the check digit I was sincerely hoping this would be easy. I thought I had hit jackpot here, since looking for data on another language written on a different script than mine is not an easy task.

As you may have already noticed my focus is to add VAT number validation in stdnum, but this country is not a top priority for me, so if you feel encouraged it is all yours.

**Comment by arthurdejong** [comment]
I managed to [find a better source](http://pravo.levonevsky.org/bazaby09/sbor37/text37892/index3.htm) for the check digit algorithm and it actually turns out the [example on Wikipedia](https://be.wikipedia.org/w/index.php?title=%D0%A3%D0%BB%D1%96%D0%BA%D0%BE%D0%B2%D1%8B_%D0%BD%D1%83%D0%BC%D0%B0%D1%80_%D0%BF%D0%BB%D0%B0%D1%86%D0%B5%D0%BB%D1%8C%D1%88%D1%87%D1%8B%D0%BA%D0%B0&stable=0#%D0%9F%D1%80%D1%8B%D0%BA%D0%BB%D0%B0%D0%B4) as well as in the [page linked on Wikipedia](http://www.pravo.by/pdf/2004-38/2004-38(010-043).pdf) was incorrect (I fixed the Wikipedia page). Researching the Russian texts was not easy. ;)

Fun fact: it turns out that the M and A in МА1953684 are actually not always the ASCII M and A but can be the Cyrillic flavour, adding another fun challenge.

**Comment by unho** [comment]
Great, another one down.

AFAICT in Europe we are only missing Ukraine, North Macedonia, Montenegro, Bosnia and Herzegovina, Liechtenstein and Faeroe Islands (and the Vatican?).
