### ISSUE TITLE
Delegate a number verification to an external service

### ISSUE THREAD

**Issue by jean-martial** [arthurdejong/python-stdnum#287]
Hello guys!

As you should know, [`python-stdnum` is used by Tryton](https://github.com/arthurdejong/python-stdnum/search?q=tryton&type=issues).

Is there a plan to delegate a number verification to an external service, for example, like [this french one](https://www.douane.gouv.fr/info-accises)?

**Comment by arthurdejong** [comment]
Hi @jean-martial,

Thanks, I know python-stdnum is used by a few CRM, ERP and financial applications (I know about e.g. Tryton, Odoo and a few commercial solutions).

For some modules a validation function is implemented that can check the number against an online resource. One problem with most of these online resources is that they are pretty subject to change and most are not meant to be queried automatically or in bulk. These checks are never part of the normal validation because that could overload the web services in certain use cases.

The linked check appears to be a VAT number validator. For European VAT numbers there is the [stdnum.eu.vat.check_vies()](https://arthurdejong.org/python-stdnum/doc/1.9/stdnum.eu.vat#stdnum.eu.vat.check_vies) function. That function also returns a dictionary with various properties that are known about the number.
