### ISSUE TITLE
Mexican RFC check digit

### ISSUE THREAD

**Issue by TrymBeast** [arthurdejong/python-stdnum#32]
The Mexican RFC check digit is being miscalculated when it should be an "A".
The example to check that is: "MAHM670102NJA".

From the document that is in the comments:
"Si el residuo es igual a 10 el dígito verificador será  “ A”."

If the remainder equals 10, then the check digit is an "A".
But the function that calculates the check digit returns "1".

**Comment by arthurdejong** [comment]
Hi,

Thanks for pointing this out. I think I worked based on a Google translate version of the document so probably missed a few things. I also found a lot of numbers that do not pass the check digit validation (that is why the check digit validation is disabled by default).

The thing in the text that is not clear to me is if the value of 10 refers to the sum modulo 11 or 11 minus that value.
Specifically, if the sum modulo 11 (S) is, the remainder (R = 11 - S) will be (R), what would the check digit (C) be (C1 is the current code, C2 is another interpretation):

 S |  R | C1 | C2
---|----|----|-----
 0 |  - |  0 |  0
 1 | 10 |  A |  1?
 2 |  9 |  9 |  9
 3 |  8 |  8 |  8
 4 |  7 |  7 |  7
 5 |  6 |  6 |  6
 6 |  5 |  5 |  5
 7 |  4 |  4 |  4
 8 |  3 |  3 |  3
 9 |  2 |  2 |  2
10 |  1 |  1 |  A?

From my test-set of about 85000 numbers with the existing calculation (C1) about 1.40% fail the check digit check, if I switch to the alternative calculation (C2) about 19.3% of the numbers fail and if both are accepted about 1.35% fail.

That seems to indicate that C1 is more likely to be correct than C2 (if my testset is OK).

Do you have any clearer sources for the check digit validation or perhaps know of an online service where numbers can be checked?

**Comment by TrymBeast** [comment]
I have just found this validator: https://portalsat.plataforma.sat.gob.mx/ConsultaRFC/

You can submit a file with maximum 5000 rfc's. Like this:

1|BAFJ701213SB10|
2|OIPF790205P26|
3|MAHM670102NJA|
4|CAGM6406181Y9|
5|CALF750228LK7|
6|OLAL701201R94|
7|ERER6711209E4|
8|SADD7808121G8|
9|SAGM690224FL0|

The problem with this validator is that it will only say that it is valid if it is really registered.

In this [site](https://exceltotal.com/generar-rfc-en-excel/) they do it like this:
```
Select Case residuo
    Case 0:
        digito = "0"
    Case 10:
        digito = "A"
    Case Else
        digito = 11 - residuo
End Select
```
But it doesn't work well because when the remainder is 1 the check digit is not a single digit, but 10.

**Comment by arthurdejong** [comment]
I made a file with about 1200 numbers that failed my original test, about 1700 that failed the second test and about 1900 that passed both tests. Of these 5 failed the online test because they contained an Ñ (probably an encoding issue) and 15 failed the check for other reasons. From these 14 also failed both check digit tests.

I ran some more parts of test list through the online service and I think I no more than 0.2% of my original list of about 85000 numbers are invalid.

This confirms my suspicion that the check digit tests results in a lot of false negatives so should not be enabled by default. I have a list of about 1200 numbers that are validated but match neither checksum.

Judging by these numbers I also think my original test is better than the alternative. The original has a false negative rate of about 1.4% while the alternative has a 19% false negative rate.

Thanks for pointing me to those resources. I have added some documentation to the module and tests and have removed a few numbers that are invalid according to the online test (see 095dcbb). Note that the number MAHM670102NJA you originally reported is also invalid according to the online test.
