### ISSUE TITLE
Australian Business Number misunderstandings

### ISSUE THREAD

**Issue by kxnes** [arthurdejong/python-stdnum#86]
Hello, @arthurdejong !

There is some problem. I got a ABN number: `07100000000`. In present algorithm in `stdnum.au.abn` I get exception like:
![selection_003](https://user-images.githubusercontent.com/32017103/48627517-d66b8580-e9c5-11e8-9c34-31df108066bd.png)
But when I verify number from Official Site, I get this one:
![selection_004](https://user-images.githubusercontent.com/32017103/48627580-f69b4480-e9c5-11e8-9936-3966d167d70e.png)

And it is confused.

**Comment by arthurdejong** [comment]
[At the Australian Business Register](https://abr.business.gov.au/ABN/View?id=07100000000) I currently get "No record found matching ABN 07 100 000 000".

Also, from my reading of [The format of the Australian
Business Number (ABN)](https://web.archive.org/web/20151223191205/http://downloads.icbglobal.org/au/ATO/ATO_Format_of_the_ABN_NAT2956.pdf) I get the impression that the first digit is not supposed to be 0.

The implementation currently generates the check ditigs and uses that to verify the number but since there may be a few numbers that could have more than one set of digits that result in a valid checksum, it could be possible that the implementation should calculate the checksum instead of generate the check digits. On the other hand most of these kind of formats only allow one form of the check digit combinations.

**Comment by kxnes** [comment]
Thanks!
